kind: Service
apiVersion: v1
metadata:
        name: webshell
spec:
        selector:
                app: webshell
        ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
